services:
  - type: web
    name: pos-server
    runtime: node
    repo: https://github.com/Mantusahoo07/server
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://pos:posd98@pos.8iiiieg.mongodb.net/pos-system?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: rzp_live_RlSrpAntWBQZ7c
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://your-frontend-url.com
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    autoDeploy: true
